image: tetraweb/php

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$STAGING_PRIVATE_KEY_ENCODED" | base64 --decode)
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stage_dev:
  environment:
    name: staging
    url: https://dev.wikiaction.org
  except:
    - master
  script:
    - ssh -p22 gael@87.98.138.147 "mkdir testGitDev/_tmp"
    - scp -P22 -r app/* gael@87.98.138.147:testGitDev/_tmp
    - ssh -p22 gael@87.98.138.147 "mv testGitDev/live testGitDev/_old && mv testGitDev/_tmp testGitDev/live"
    - ssh -p22 gael@87.98.138.147 "rm -rf testGitDev/_old"

production:
  environment: production
  only:
    - master
  script:
    - ssh -p22 gael@87.98.138.147 "mkdir testGitMaster/_tmp"
    - scp -P22 -r app/* gael@87.98.138.147:testGitMaster/_tmp
    - ssh -p22 gael@87.98.138.147 "mv testGitMaster/live testGitMaster/_old && mv testGitMaster/_tmp testGitMaster/live"
    - ssh -p22 gael@87.98.138.147 "rm -rf testGitMaster/_old"

